name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=chocolate&color_dots[0]=antiquewhite&color_dots[1]=peru&color_dots[2]=sienna&color_dots[3]=saddlebrown&color_dots[4]=maroon
            dist/github-contribution-grid-snake-dark.svg?color_snake=darkorange&color_dots[0]=black&color_dots[1]=saddlebrown&color_dots[2]=sienna&color_dots[3]=chocolate&color_dots[4]=darkorange

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
